// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImportService cobre a História 3: varrer a pasta de armazenamento em
 * busca de vídeos de aula ainda não registrados, listar os candidatos
 * pendentes de revisão e confirmar um deles (data/tutor) como lesson real.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ConfirmImport grava o candidato id como lesson real (lessonDate no
 * formato AAAA-MM-DDTHH:MM, tutor livre) e cria os jobs de processamento. Depois
 * de confirmar, tenta calcular a duração do vídeo (melhor esforço — ver
 * setDurationBestEffort).
 */
export function ConfirmImport(id: number, lessonDate: string, tutor: string): $CancellablePromise<void> {
    return $Call.ByID(1948496713, id, lessonDate, tutor);
}

/**
 * DropImport processa arquivos recebidos via drag-and-drop nativo do
 * Wails (main.go chama isso a partir do evento WindowFilesDropped) — um
 * candidato pendente por arquivo válido, reaproveitando a mesma dedupe
 * por hash da varredura (História 3). Diferente do best-effort de
 * renameVideoBestEffort, falha aqui é sempre reportada (via
 * DropErrorEvent e no DropResult retornado) — sem um candidato em
 * pending_imports o usuário não teria outro jeito de saber que o arquivo
 * solto falhou.
 */
export function DropImport(paths: string[] | null): $CancellablePromise<$models.DropResult[] | null> {
    return $Call.ByID(28488448, paths);
}

/**
 * ListPendingImports lista os candidatos aguardando revisão, pra seção
 * "aguardando revisão" da Biblioteca.
 */
export function ListPendingImports(): $CancellablePromise<$models.PendingImport[] | null> {
    return $Call.ByID(3801261335);
}

/**
 * ScanFolder varre storage_root (de config.Load) e atualiza pending_imports
 * e lessons. Chamado automaticamente ao final do wizard de first-run e sob
 * demanda pelo botão "Sincronizar pasta" da Biblioteca.
 */
export function ScanFolder(): $CancellablePromise<$models.ScanSummary> {
    return $Call.ByID(2859972501);
}
