// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DropResult é o resultado de processar um caminho recebido via
 * drag-and-drop nativo (main.go, evento WindowFilesDropped) — usado como
 * retorno de DropImport (testável) e também como payload do evento
 * DropErrorEvent quando Error não é vazio.
 */
export interface DropResult {
    "path": string;
    "error": string;
}

/**
 * Lesson é uma aula confirmada, no formato exposto ao frontend. Status é
 * sempre um de "processando", "pronta", "erro" (ver db.LessonWithStatus);
 * ErrorMessage só é preenchido quando Status == "erro". DurationSeconds é
 * nil até o probe de duração (melhor esforço, na confirmação da
 * importação) ter sucesso. StudentSpeakerLabel é nil até o usuário marcar
 * quem é o aluno no toggle do Detalhe (História 6).
 */
export interface Lesson {
    "id": number;
    "lessonDate": string;
    "tutor": string;
    "videoPath": string;
    "durationSeconds": number | null;
    "status": string;
    "errorMessage": string;
    "studentSpeakerLabel": string | null;
}

/**
 * LessonFilter filtra ListLessons — campos vazios são ignorados (sem
 * filtro naquele critério).
 */
export interface LessonFilter {
    "tutor": string;
    "dateFrom": string;
    "dateTo": string;
}

/**
 * PendingImport é um candidato aguardando revisão, no formato exposto ao
 * frontend — só o que o modal de confirmação precisa mostrar.
 */
export interface PendingImport {
    "id": number;
    "path": string;
    "suggestedDate": string;
}

/**
 * QueueItem é uma entrada da fila, no formato exposto ao frontend.
 */
export interface QueueItem {
    "lessonId": number;
    "lessonDate": string;
    "tutor": string;
    "stage": string;
    "status": string;
    "attempts": number;
    "lastError": string;
}

/**
 * ScanSummary é o resultado de uma varredura, exposto ao frontend pra um
 * toast de resumo ("N novas, M atualizadas, E erros").
 */
export interface ScanSummary {
    "new": number;
    "updated": number;
    "skipped": number;
    "errors": number;
}

/**
 * Transcript é a transcrição de uma lesson, no formato exposto ao Detalhe
 * (História 6).
 */
export interface Transcript {
    "utterances": Utterance[] | null;
}

/**
 * Utterance é uma fala da transcrição. Timestamps em segundos — mesma
 * unidade de HTMLVideoElement.currentTime no frontend, convertida aqui na
 * borda do serviço (o banco guarda time.Duration).
 */
export interface Utterance {
    "speaker": string;
    "text": string;
    "startSeconds": number;
    "endSeconds": number;
}
